#  DISCORD EMBED TITLE LIMIT = 256 CHARACTERS
#  0                                                                                                   1                                                                                                   2
#  0         1         2         3         4         5         6         7         8         9         0         1         2         3         4         5         6         7         8         9         0         1         2         3         4         5
#  01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456

TOD_TRUTHS = [
  ["What's the longest gaming session you've ever had, and what game were you playing?","ajgoh"],
  ["Which game do you rage-quit the most?","ajgoh"],
  ["What's your most embarrassing in-game moment?","ajgoh"],
  ["If you were to live in a game, which game would you thrive in?","ajgoh"],
  ["If you were to live in a game, which game would you suffer the most in?","ajgoh"],
  ["Who is the best team player in the server?","ajgoh"],
  ["Who is the worst team player in the server?","ajgoh"],
  ["What's the biggest lie you've ever told about your gaming skills?","ajgoh"],
  ["What's the most money you've spent on a game pass or cosmetic item?","ajgoh"],
  ["If you could only play one game for the rest of your life, which one would it be?","ajgoh"],
  ["How many people in the server do you like?","kenjiblue_"],
  ["who do you dislike the most in the server?","callmebrody"],
  ["How much Robux do you _actually_ have?","callmebrody"],
  ["What was the most goofiest thing you said in the server?","callmebrody"],
  ["Have you ever trolled/scammed someone on Roblox?","callmebrody"],
  ["How old are you?","callmebrody"],
  ["Do you have any siblings, and if so how many of them use Discord?","callmebrody"],
  ["What was the last thing you ate?","callmebrody"],
  ["How many friends do you have?","callmebrody"],
  ["What was the most unhinged thing you said in the server?","callmebrody"],
  ["Have you wet the bed recently?","callmebrody"],
  ["Are you a furry?","callmebrody"],
  ["What was the weirdest game you've played, and did you like it?","callmebrody"],
  ["Have you ever kissed someone?","callmebrody"],
  ["What's the most embarrassing thing you've ever done?","iamtheoneandonly123_88207"],
  ["What's your biggest fear?","iamtheoneandonly123_88207"],
  ["What's the worst gift you've ever received?","iamtheoneandonly123_88207"],
  ["What's a secret you've never told anyone?","iamtheoneandonly123_88207"],
  ["Have you ever been caught doing something you shouldn't have?","iamtheoneandonly123_88207"],
  ["Have you ever had a near-death experience?","iamtheoneandonly123_88207"],
  ["Who is your biggest enemy?","iamtheoneandonly123_88207"],
  ["What's your very first Discord username?","iamtheoneandonly123_88207"],
  ["What's your very first Roblox username?","iamtheoneandonly123_88207"],
  ["Have you ever experienced a heart attack from a horror game or movie?","iamtheoneandonly123_88207"],
  ["What's your hottest take on the worst popular anime?","wantlike"],
  ["What's an 'underrated' anime that you like?","wantlike"],
  ["What's your favourite game genre?","wantlike"],
  ["How many times have you swore after dying in a game?","wantlike"],
  ["Why did you join AJ's Paradise?","wantlike"],
  ["Out of everyone in the server, who do you think is the worst, best, mosy annoying, and favourite person?","wantlike"],
  ["How did you act when you first joined Roblox?","wantlike"],
  ["When was the last time you showered?","ragvindr"],
  ["Have you ever tried creating a game before?","ragvindr"],
  ["What's the weirdest you've set your Discord/Roblox username to?","jacoolbins"],
  ["What do you do in your spare time?","jacoolbins"],
  ["have you ever used ChatGPT or any kind of AI to cheat in something?","jacoolbins"],
  ["What is your favourite subject in school, and why?","jacoolbins"],
  ["Do you wish you were somebody else, and if so who and why?","jacoolbins"],
  ["What do you think is your inside-outside ratio?","jacoolbins"],
  ["Can you do skateboard/scooter stunts?","jacoolbins"],
  ["If you could live anywhere in the world, where would it be?","jacoolbins"],
  ["Where do you wish to go in the world?","jacoolbins"],
  ["Sock-shoe-sock-shoe or sock-sock-show-shoe?","jacoolbins"],
  ["Best platform? (Minecraft, Roblox, Fornite, etc.)","jacoolbins"],
  ["Favourite meal? (Breakfast, lunch, dinner, etc.)","jacoolbins"],
  ["How many wins do you have in Roblox BedWars?","jacoolbins"],
  ["If you could live the life of AJ Goh for a day (as if you're possessing his body and living where he lives and doing what he does), what would you do? (You have access to all of his memories and possessions)","jacoolbins"],
  ["Do you use Duolingo, and if so what is your current and highest streak?","jacoolbins"],
  ["Worst vegetable?","jacoolbins"],
  ["Have you ever slept with someone of the same gender as you? (Family and relatives don't count)","jacoolbins"],
  ["Have you ever slept with someone of the opposite gender from you? (Family and relatives don't count)","jacoolbins"],
  ["Do you have a lover?","jacoolbins"],
  ["Mobile or PC?","jacoolbins"],
  ["How many Discord servers are you in?","jacoolbins"],
  ["If you could be an animal or object, what would it be? (Interesting responses encouraged - eg. a raindrop, a pyramid)","jacoolbins"],
  ["Best game on Roblox?","jacoolbins"],
  ["Skimmed milk or full cream milk?","jacoolbins"],
  ["Do you own a plushie, and if so what is it and where do you put it?","jacoolbins"],
  ["If you could be friends with a fictional character, who would it be?","jacoolbins"],
  ["If you could remove one thing from existence, what would it be?","jacoolbins"],
  ["What's your device's current battery percentage?","jacoolbins"],
  ["What are your goals in life (if any)?","jacoolbins"],
  ["What's the best place you've every visited?","jacoolbins"],
  ["Pancakes or waffles?","jacoolbins"],
  ["Have you ever got the urge to murder someone?","jacoolbins"],
  ["What's something you hate? (eg. when you flip the pillow but it's not cold)","jacoolbins"],
  ["If you had to add something to the server and remove something else in exchange, what would they be?","jacoolbins"]
]

TOD_DARES = [
  ["Change your Discord username to '`i am a noob`' for a day.","ajgoh"],
  ["Change your Roblox display name to '`i am a noob`' for a week.","ajgoh"],
  ["Play your most hated game with a friend for an hour and share your experience.","ajgoh"],
  ["For your next match, play with your controls inverted and share the results.","ajgoh"],
  ["Post a picture of your current gaming setup, no matter how messy it is.","ajgoh"],
  ["Write a poem about something or someone.","kenjiblue_"],
  ["Change your profile picture to the most recently sent image for a day.","callmebrody"],
  ["Change your Roblox avatar to whatever the first person says for a day.","callmebrody"],
  ["Pretend to confess your love for someone in DMs, and post their reaction <3","callmebrody"],
  ["Act like an underaged Discord user for the next few minutes.","callmebrody"],
  ["Act a little _zesty_ for the next few minutes.","callmebrody"],
  ["Share the last message you sent in DMs.","callmebrody"],
  ["Share the last message you received in DMs.","callmebrody"],
  ["DM someone 'I think I'm pregnant' without context.","callmebrody"],
  ["Eat whatever the first person says.","callmebrody"],
  ["Block a random Discord friend for a day.","callmebrody"],
  ["Pretend to be a furry for a day.","callmebrody"],
  ["Change your profile picture to that of an anime girl for a day.","callmebrody"],
  ["Play whatever game the first person says.","callmebrody"],
  ["Eat pizza!","callmebrody"],
  ["Create a dare and dare yourself to do your dare.","callmebrody"],
  ["Create a dare and dare someone to do your dare.","callmebrody"],
  ["Do whatever dare the first person says.","callmebrody"],
  ["Unborn yourself.","callmebrody"],
  ["Play Fortnite for 5 hours straight.","iamtheoneandonly123_88207"],
  ["Jump around in your room blindfolded for 5 minutes, trying not to bump into anything.","iamtheoneandonly123_88207"],
  ["Let your intrusive thoughts win for a moment and see what happens...","iamtheoneandonly123_88207"],
  ["Ignore someone for a day and see their reaction.","iamtheoneandonly123_88207"],
  ["Show how much Robux you currently have.","wantlike"],
  ["Play Tower of Hell for 10 minutes.","wantlike"],
  ["Act like the person you hate most in the server.","wantlike"],
  ["Spam ping someone's DMs.","wantlike"],
  ["Drink several cups of water.","wantlike"],
  ["Go outside, look for grass and post a picture of you touching some.","wantlike"],
  ["Play an FPS (First Person Shooter) game and record yourself getting a 7-to-1 Kill/Death ratio.","wantlike"],
  ["Play an RNG (Random Number Generator) game you've never played before.","wantlike"],
  ["Answer a truth now instead of doing a dare.","wantlike"],
  ["Pretend to seek for therapy in the server until someone who tries to help you.","wantlike"],
  ["Draw for an hour and share your creation.","wantlike"],
  ["Go take a shower.","ragvindr"],
  ["Attempt to create a game based on AJ's Paradise.","ragvindr"],
  ["If you're in Kyoto, go to a nearby restaurant to order a bowl of ramen, and post a picture of it. Afterwards, go to a store to buy two plushies, and post a picture of them. Finally, return home and send a message saying 'Another day, another weird things.'","aurumx_z"],
  ["Eat something you've never eaten before.","jacoolbins"],
  ["Draw AJ's logo but in greyscale so that it looks like an old photo.","jacoolbins"],
  ["Head outside and pluck a blade of grass, take it home with you and place it by your computer setup - as a reminder to go outside and touch grass whenever possible ;)","jacoolbins"],
  ["Fill in and submit a staff application form while pretending to be a 95-year-old grandma in Icelend trying to execute your plan to live on Mars and do yoga with an alien there.","jacoolbins"],
  ["Beat 'Stereo Madness' in Geometry Dash (good luck!)","jacoolbins"],
  ["Make a milkshake with butter, banana and broccoli...","jacoolbins"],
  ["Change your profile picture and see how long it takes for someone to notice.","jacoolbins"],
  ["Don't use the letter 'a' in your messages for a day.","jacoolbins"],
  ["Don't use the letter 'e' in your messages for a day.","jacoolbins"],
  ["Use a different device to chat on Discord for a day.","jacoolbins"],
  ["Change your server nickname to something randomly generated by ChatGPT.","jacoolbins"],
  ["||Chat only in spoilers for a day :0|| (`||text||`)","jacoolbins"],
  ["_Chat only in italics for a day :0_ (`_text_`)","jacoolbins"],
  ["Rhyme every 2 messages you send for a day.","jacoolbins"],
  ["Say 'hi'/'bye' to others in a different language each time for a day.","jacoolbins"],
  ["Ping AJ and if he doesnt reply you're ga-","jacoolbins"]
]